spring:
  ai:
    deepseek:
      chat:
        # 可以通过${xxx}从环境变量中获取,去https://www.deepseek.com/充值申请
        api-key: ${DEEPSEEK_API_KEY}
        # 文档: https://api-docs.deepseek.com/zh-cn/
        model: deepseek-v4-pro
        # 默认已配置,可以不用配置
        base-url: https://api.deepseek.com
    # ollama配置
    ollama:
      # 默认http://localhost:11434
      base-url: http://localhost:11434
      chat:
        # 你在ollama上运行的模型名字
        model: deepseek-r1
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        model: deepseek-v4-pro
        # 默认为https://api.openai.com
        # 因为是open ai风格,OpenAiChatModel会自动在baseUrl后附加/chat/completions
        # 最终请求路径为: https://api.deepseek.com/chat/completions
        base-url: https://api.deepseek.com
    anthropic:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        model: deepseek-v4-pro
      # 默认为https://api.anthropic.com
      base-url: https://api.deepseek.com/anthropic
